#Define an environment variable for a container 
#List the running Pods:
#kubectl get pods -l purpose=demonstrate-envars
#List the Pod's container environment variables:
#kubectl exec envar-demo -- printenv
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
