apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    env: prod
    status: critical
  annotations:
    imageregistry: "https://console.aws.amazon.com/systems-manager/session-manager/i-006703aa70009f459?region=us-east-1"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-for-development-namespace
  namespace: development
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-development-namespace
  namespace: prod
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container
