apiVersion: v1
kind: Pod
metadata:
  name: default-mem-demo-2
  namespace: prod
spec:
  containers:
  - name: default-mem-demo-2-ctr
    image: nginx
    resources:
      limits:
        memory: "1Gi"
