apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-storage-pv
  labels:
    type: local
spec:
  storageClassName: mylocal
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/data"
