apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
  namespace: auth
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: host-storage-pvc
  containers:
    - name: pv-pod
      image: busybox
      command: ['sh','-c','while true; do echo success > /output/output.log; sleep 5; done']
      volumeMounts:
        - mountPath: "/output"
          name: task-pv-storage
